name: education
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
   - assets/images/book.png
   - assets/images/Education.png
   - assets/images/images.png
   - assets/images/flutter.png
   - assets/images/cSharp.png
   - assets/images/React Native.png
   - assets/images/python.png
   


  uses-material-design: true
